"""empty message

Revision ID: 9145cc440cb3
Revises: bf1e094782ae
Create Date: 2022-11-13 18:39:31.472165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9145cc440cb3'
down_revision = 'bf1e094782ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
