"""empty message

Revision ID: bf1e094782ae
Revises: c6f49befec47
Create Date: 2022-11-13 18:37:29.311395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf1e094782ae'
down_revision = 'c6f49befec47'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
